import React from 'react';

// Mock TaroJS components for testing
export const View: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const Text: React.FC<any> = ({ children, ...props }) => <span {...props}>{children}</span>;
export const Image: React.FC<any> = (props) => <img alt="mock-image" {...props} />;
export const Button: React.FC<any> = ({ children, ...props }) => <button {...props}>{children}</button>;
export const Input: React.FC<any> = (props) => <input {...props} />;
export const Textarea: React.FC<any> = (props) => <textarea {...props} />;
export const ScrollView: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const Swiper: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const SwiperItem: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const Icon: React.FC<any> = (props) => <span {...props} />;
export const Navigator: React.FC<any> = ({ children, ...props }) => <a {...props}>{children}</a>;
export const Form: React.FC<any> = ({ children, ...props }) => <form {...props}>{children}</form>;
export const Label: React.FC<any> = ({ children, ...props }) => <label {...props}>{children}</label>;
export const Radio: React.FC<any> = (props) => <input type="radio" {...props} />;
export const RadioGroup: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const Checkbox: React.FC<any> = (props) => <input type="checkbox" {...props} />;
export const CheckboxGroup: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const Switch: React.FC<any> = (props) => <input type="checkbox" {...props} />;
export const Slider: React.FC<any> = (props) => <input type="range" {...props} />;
export const Picker: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const PickerView: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const PickerViewColumn: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const Modal: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const Progress: React.FC<any> = (props) => <progress {...props} />;
export const RichText: React.FC<any> = (props) => {
  // eslint-disable-next-line react/no-danger-with-children
  return <div dangerouslySetInnerHTML={{ __html: props.nodes || '' }} {...props} />;
};
export const OpenData: React.FC<any> = (props) => <div {...props} />;
export const WebView: React.FC<any> = (props) => <iframe title="webview" {...props} />;
export const Canvas: React.FC<any> = (props) => <canvas {...props} />;
export const Map: React.FC<any> = (props) => <div {...props} />;
export const Video: React.FC<any> = (props) => <video {...props} />;
export const Camera: React.FC<any> = (props) => <div {...props} />;
export const Audio: React.FC<any> = (props) => <audio {...props} />;
export const Ad: React.FC<any> = (props) => <div {...props} />;
export const OfficialAccount: React.FC<any> = (props) => <div {...props} />;
export const NavigationBar: React.FC<any> = (props) => <div {...props} />;
export const PageMeta: React.FC<any> = (props) => <div {...props} />;
export const Block: React.FC<any> = ({ children, ...props }) => <>{children}</>;
export const MovableArea: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const MovableView: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const CoverView: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const CoverImage: React.FC<any> = (props) => <img alt="cover" {...props} />;
export const Editor: React.FC<any> = (props) => <div {...props} />;
export const MatchMedia: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const RootPortal: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const ShareElement: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const KeyboardAccessory: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const VoipRoom: React.FC<any> = (props) => <div {...props} />;
export const AdCustom: React.FC<any> = (props) => <div {...props} />;
export const PageContainer: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const GridView: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const Snapshot: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const StickyHeader: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const StickySection: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const GridBuilder: React.FC<any> = (props) => <div {...props} />;
export const ListView: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const ListBuilder: React.FC<any> = (props) => <div {...props} />;
export const NestedScrollHeader: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
export const NestedScrollBody: React.FC<any> = ({ children, ...props }) => <div {...props}>{children}</div>;
